import fs from 'fs';

const data = fs.readFileSync('src/data.js', 'utf8');

const markers = [
  '[SDLC_COMPONENT]',
  '[ALGORITHM_COMPONENT]',
  '[LANGUAGE_LEVELS_COMPONENT]',
  '[PYTHON_STRUCTURE_COMPONENT]',
  '[CONTROL_FLOW_COMPONENT]',
  '[MEMORY_COMPONENT]',
  '[FUNCTION_COMPONENT]',
  '[ERROR_HANDLING_COMPONENT]',
  '[MINI_POS_COMPONENT]',
  '[PROGRAM_MEANING_COMPONENT]',
  '[TRANSLATOR_COMPARE_COMPONENT]',
  '[PYTHON_TIMELINE_COMPONENT]',
  '[SETUP_GUIDE_COMPONENT]',
  '[PYTHONIC_WAY_COMPONENT]',
  '[INDENTATION_DEMO_COMPONENT]',
  '[FLOWCHART_SYMBOLS_COMPONENT]',
  '[SEQUENCE_FLOWCHART_COMPONENT]',
  '[SELECTION_FLOWCHART_COMPONENT]',
  '[ITERATION_FLOWCHART_COMPONENT]',
  '[FLOWCHART_BEST_PRACTICE_COMPONENT]',
  '[PSEUDOCODE_INTRO_COMPONENT]',
  '[PSEUDOCODE_KEYWORDS_COMPONENT]',
  '[PSEUDOCODE_CONDITION_COMPONENT]',
  '[PSEUDOCODE_LOOP_COMPONENT]',
  '[PSEUDOCODE_FORMAT_COMPONENT]',
  '[NAMING_CONVENTION_COMPONENT]',
  '[INTEGER_EXPLORER_COMPONENT]',
  '[FLOAT_EXPLORER_COMPONENT]',
  '[STRING_EXPLORER_COMPONENT]',
  '[BOOLEAN_EXPLORER_COMPONENT]',
  '[IMPORT_MODULE_COMPONENT]',
  '[INPUT_DEMO_COMPONENT]',
  '[PRINT_FORMAT_COMPONENT]',
  '[ARITHMETIC_OPS_COMPONENT]',
  '[ASSIGNMENT_OPS_COMPONENT]',
  '[COMPARISON_OPS_COMPONENT]',
  '[LOGICAL_OPS_COMPONENT]',
  '[IDENTITY_OPS_COMPONENT]',
  '[MEMBERSHIP_OPS_COMPONENT]',
  '[BITWISE_OPS_COMPONENT]',
  '[IF_STATEMENT_COMPONENT]',
  '[ELIF_STATEMENT_COMPONENT]',
  '[ELSE_STATEMENT_COMPONENT]',
  '[WHILE_LOOP_COMPONENT]',
  '[FOR_LOOP_COMPONENT]',
  '[RANGE_FUNCTION_COMPONENT]',
  '[LIST_EXPLORER_COMPONENT]',
  '[TUPLE_DICT_COMPONENT]',
  '[SET_STRING_COMPONENT]',
  '[BUILTIN_FUNCTIONS_COMPONENT]',
  '[DEF_FUNCTION_COMPONENT]',
  '[RETURN_SCOPE_COMPONENT]',
  '[BUSINESS_DESIGN_COMPONENT]',
  '[BUSINESS_LOGIC_COMPONENT]',
  '[FILE_HANDLER_COMPONENT]',
  '[DOC_GENERATOR_COMPONENT]'
];

const unused = [];
markers.forEach(marker => {
  if (!data.includes(marker)) {
    unused.push(marker);
  }
});

console.log("Unused markers:", unused);
